name: Build & Prettify Code

on:
  push:
    branches-ignore:
      - main

jobs:
  version_check:
    if: |
      !startsWith(github.event.head_commit.message, 'chore: merge changes after release') &&
      !startsWith(github.event.head_commit.message, 'chore: prettify code')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check version mismatch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "[i] Checking if the version in the CHANGELOG.md and package.json version matches"
          PACKAGE_JSON_VERSION=$(cat package.json | jq ".version" -r)
          CHANGELOG_VERSION=$(cat CHANGELOG.md | grep -E "^## [0-9]+\.[0-9]+\.[0-9]+(-(alpha|beta)(\.[0-9]+)?)?" | head -n 1 | sed -E 's/^## ([0-9]+\.[0-9]+\.[0-9]+(-(alpha|beta)(\.[0-9]+)?)?).*/\1/')
          GLOBALS_FILE_VERSION=$(grep -E '^const version =.+' src/globalConfig.ts | sed -E 's/^const version = \"(.*)\";/\1/')
          if [[ "$PACKAGE_JSON_VERSION" != "$CHANGELOG_VERSION" ]]; then
            echo "Version number mismatch between PACKAGE_JSON_VERSION and CHANGELOG_VERSION"
            exit 1
          elif [[ "$PACKAGE_JSON_VERSION" != "$GLOBALS_FILE_VERSION" ]]; then
            echo "Version number mismatch between PACKAGE_JSON_VERSION and GLOBALS_FILE_VERSION"
            exit 1
          else
            echo "[✓] Version matches"
            echo "[i] Checking if the version already exists on GitHub"
            if gh release view "v$PACKAGE_JSON_VERSION" >/dev/null 2>&1; then
              echo "Version v$PACKAGE_JSON_VERSION already exists on GitHub."
              exit 1
            else
              echo "[✓] Version v$PACKAGE_JSON_VERSION does not exist on GitHub."
            fi
          fi

  prettier:
    runs-on: ubuntu-latest
    needs: version_check
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the action checks out the repository to the pull request branch
          ref: ${{ github.ref_name }}
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Prettier
        run: npm install -g prettier

      - name: Run Prettier
        run: prettier --write . --config .prettierrc
      
      - name: Remove node_modules
        run: rm -rf node_modules

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: prettify code" || echo "No changes to commit"
          git push

  build:
    needs: prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the action checks out the repository to the pull request branch
          ref: ${{ github.ref_name }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build
  build-docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the action checks out the repository to the pull request branch
          ref: ${{ github.ref_name }}
      - name: Build docker container
        run: docker build -t shriyanss/js-recon .
